In [1]:
from datetime import date
import polars as pl
from flights.evaluation.evaluation import main
test_date = date(2026,3,1)
results, df_stats = main(test_src="adsbx", gold_src="sfdps", test_dates = test_date)
df = results[0]

Loading airports from /Volumes/T2-SSD/planequery/data/raw/ourairports/airports.csv
Stats for adsbx:sfdps: {'true_positive': 6244, 'false_positive': 31, 'false_negative': 484, 'precision': 0.9950597609561753, 'recall': 0.9280618311533888, 'f1': 0.9603937552872414, 'takeoff_airport_ident_match_pct': 0.9985586162716208, 'landing_airport_ident_match_pct': 0.9990390775144138, 'airport_ident_match_pct': 0.9975976937860346}
Stats CSV saved to /Volumes/T2-SSD/planequery/data/experiments/comparison/2026-07-15_07-32_ea042da_flights_evaluation.csv

In [3]:
df.filter(pl.col("icao") == "a004e9")

shape: (1, 51)
┌────────┬──────────┬────────────┬────────────┬───┬────────────┬───────────┬───────────┬───────────┐
│ icao   ┆ callsign ┆ registrati ┆ takeoff_ti ┆ … ┆ first_mess ┆ last_mess ┆ first_mes ┆ last_mess │
│ ---    ┆ ---      ┆ on         ┆ me         ┆   ┆ age_time_d ┆ age_time_ ┆ sage_dist ┆ age_dista │
│ str    ┆ str      ┆ ---        ┆ ---        ┆   ┆ iff        ┆ diff      ┆ ance_to_t ┆ nce_to_la │
│        ┆          ┆ str        ┆ datetime[m ┆   ┆ ---        ┆ ---       ┆ ake…      ┆ ndi…      │
│        ┆          ┆            ┆ s]         ┆   ┆ duration[m ┆ duration[ ┆ ---       ┆ ---       │
│        ┆          ┆            ┆            ┆   ┆ s]         ┆ ms]       ┆ f64       ┆ f64       │
╞════════╪══════════╪════════════╪════════════╪═══╪════════════╪═══════════╪═══════════╪═══════════╡
│ a004e9 ┆ null     ┆ null       ┆ null       ┆ … ┆ null       ┆ null      ┆ null      ┆ null      │
└────────┴──────────┴────────────┴────────────┴───┴────────────┴───────────┴───────────┴───────────┘

In [6]:
COLUMNS = ["icao", "takeoff_time", "landing_time", "takeoff_airport_ident", "landing_airport_ident", "takeoff_time_df1", "landing_time_df1", "takeoff_airport_ident_df1", "landing_airport_ident_df1", "match_status"]
df.filter(pl.col("icao") == "a003a8").select(COLUMNS)

shape: (3, 10)
┌────────┬────────────┬────────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ icao   ┆ takeoff_ti ┆ landing_ti ┆ takeoff_a ┆ … ┆ landing_t ┆ takeoff_a ┆ landing_a ┆ match_sta │
│ ---    ┆ me         ┆ me         ┆ irport_id ┆   ┆ ime_df1   ┆ irport_id ┆ irport_id ┆ tus       │
│ str    ┆ ---        ┆ ---        ┆ ent       ┆   ┆ ---       ┆ ent_df1   ┆ ent_df1   ┆ ---       │
│        ┆ datetime[m ┆ datetime[m ┆ ---       ┆   ┆ datetime[ ┆ ---       ┆ ---       ┆ str       │
│        ┆ s]         ┆ s]         ┆ str       ┆   ┆ ms]       ┆ str       ┆ str       ┆           │
╞════════╪════════════╪════════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ a003a8 ┆ null       ┆ null       ┆ null      ┆ … ┆ 2026-03-0 ┆ KBCT      ┆ MYEN      ┆ df1_only  │
│        ┆            ┆            ┆           ┆   ┆ 1         ┆           ┆           ┆           │
│        ┆            ┆            ┆           ┆   ┆ 18:59:00  ┆           ┆           ┆           │
│ a003a8 ┆ null       ┆ null       ┆ null      ┆ … ┆ 2026-03-0 ┆ MYEN      ┆ KFXE      ┆ df1_only  │
│        ┆            ┆            ┆           ┆   ┆ 1         ┆           ┆           ┆           │
│        ┆            ┆            ┆           ┆   ┆ 20:52:00  ┆           ┆           ┆           │
│ a003a8 ┆ 2026-03-01 ┆ 2026-03-01 ┆ KBCT      ┆ … ┆ null      ┆ null      ┆ null      ┆ df0_only  │
│        ┆ 18:08:13   ┆ 20:52:44   ┆           ┆   ┆           ┆           ┆           ┆           │
└────────┴────────────┴────────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [ ]:
# a003a8 wasen't in data before now it may be with adsbx used for flights matching.

In [4]:
df.filter(pl.col("match_status") == "df0_only")

shape: (31, 51)
┌────────┬──────────┬────────────┬────────────┬───┬────────────┬───────────┬───────────┬───────────┐
│ icao   ┆ callsign ┆ registrati ┆ takeoff_ti ┆ … ┆ first_mess ┆ last_mess ┆ first_mes ┆ last_mess │
│ ---    ┆ ---      ┆ on         ┆ me         ┆   ┆ age_time_d ┆ age_time_ ┆ sage_dist ┆ age_dista │
│ str    ┆ str      ┆ ---        ┆ ---        ┆   ┆ iff        ┆ diff      ┆ ance_to_t ┆ nce_to_la │
│        ┆          ┆ str        ┆ datetime[m ┆   ┆ ---        ┆ ---       ┆ ake…      ┆ ndi…      │
│        ┆          ┆            ┆ s]         ┆   ┆ duration[m ┆ duration[ ┆ ---       ┆ ---       │
│        ┆          ┆            ┆            ┆   ┆ s]         ┆ ms]       ┆ f64       ┆ f64       │
╞════════╪══════════╪════════════╪════════════╪═══╪════════════╪═══════════╪═══════════╪═══════════╡
│ a003a8 ┆ null     ┆ N10PH      ┆ 2026-03-01 ┆ … ┆ null       ┆ null      ┆ null      ┆ null      │
│        ┆          ┆            ┆ 18:08:13   ┆   ┆            ┆           ┆           ┆           │
│ a09d74 ┆ null     ┆ N139JM     ┆ 2026-03-01 ┆ … ┆ null       ┆ null      ┆ null      ┆ null      │
│        ┆          ┆            ┆ 18:00:13   ┆   ┆            ┆           ┆           ┆           │
│ a0af5a ┆ null     ┆ N143RP     ┆ 2026-03-01 ┆ … ┆ null       ┆ null      ┆ null      ┆ null      │
│        ┆          ┆            ┆ 17:20:29   ┆   ┆            ┆           ┆           ┆           │
│ a1a4a7 ┆ null     ┆ N205AS     ┆ 2026-03-01 ┆ … ┆ null       ┆ null      ┆ null      ┆ null      │
│        ┆          ┆            ┆ 15:40:08   ┆   ┆            ┆           ┆           ┆           │
│ a1a4a7 ┆ null     ┆ N205AS     ┆ 2026-03-01 ┆ … ┆ null       ┆ null      ┆ null      ┆ null      │
│        ┆          ┆            ┆ 17:23:47   ┆   ┆            ┆           ┆           ┆           │
│ …      ┆ …        ┆ …          ┆ …          ┆ … ┆ …          ┆ …         ┆ …         ┆ …         │
│ aa69e0 ┆ null     ┆ N770JS     ┆ 2026-03-01 ┆ … ┆ null       ┆ null      ┆ null      ┆ null      │
│        ┆          ┆            ┆ 16:00:11   ┆   ┆            ┆           ┆           ┆           │
│ aa9d1a ┆ null     ┆ N783QS     ┆ 2026-03-01 ┆ … ┆ null       ┆ null      ┆ null      ┆ null      │
│        ┆          ┆            ┆ 15:40:47   ┆   ┆            ┆           ┆           ┆           │
│ aae0db ┆ null     ┆ N80PT      ┆ 2026-03-01 ┆ … ┆ null       ┆ null      ┆ null      ┆ null      │
│        ┆          ┆            ┆ 14:03:33   ┆   ┆            ┆           ┆           ┆           │
│ ac2203 ┆ null     ┆ N881EU     ┆ 2026-03-01 ┆ … ┆ null       ┆ null      ┆ null      ┆ null      │
│        ┆          ┆            ┆ 18:16:30   ┆   ┆            ┆           ┆           ┆           │
│ adccd0 ┆ null     ┆ N989CL     ┆ 2026-03-01 ┆ … ┆ null       ┆ null      ┆ null      ┆ null      │
│        ┆          ┆            ┆ 17:43:27   ┆   ┆            ┆           ┆           ┆           │
└────────┴──────────┴────────────┴────────────┴───┴────────────┴───────────┴───────────┴───────────┘

In [7]:
import polars as pl
df.filter(pia_or_american_ladd_expr()).filter(pl.col("match_status") == "df0_only")

shape: (453, 51)
┌────────┬──────────┬────────────┬────────────┬───┬────────────┬───────────┬───────────┬───────────┐
│ icao   ┆ callsign ┆ registrati ┆ takeoff_ti ┆ … ┆ first_mess ┆ last_mess ┆ first_mes ┆ last_mess │
│ ---    ┆ ---      ┆ on         ┆ me         ┆   ┆ age_time_d ┆ age_time_ ┆ sage_dist ┆ age_dista │
│ str    ┆ str      ┆ ---        ┆ ---        ┆   ┆ iff        ┆ diff      ┆ ance_to_t ┆ nce_to_la │
│        ┆          ┆ str        ┆ datetime[m ┆   ┆ ---        ┆ ---       ┆ ake…      ┆ ndi…      │
│        ┆          ┆            ┆ s]         ┆   ┆ duration[m ┆ duration[ ┆ ---       ┆ ---       │
│        ┆          ┆            ┆            ┆   ┆ s]         ┆ ms]       ┆ f64       ┆ f64       │
╞════════╪══════════╪════════════╪════════════╪═══╪════════════╪═══════════╪═══════════╪═══════════╡
│ a001de ┆ null     ┆ N1VA       ┆ 2026-03-01 ┆ … ┆ null       ┆ null      ┆ null      ┆ null      │
│        ┆          ┆            ┆ 15:04:52   ┆   ┆            ┆           ┆           ┆           │
│ a003a8 ┆ null     ┆ N10PH      ┆ 2026-03-01 ┆ … ┆ null       ┆ null      ┆ null      ┆ null      │
│        ┆          ┆            ┆ 18:08:13   ┆   ┆            ┆           ┆           ┆           │
│ a014b5 ┆ null     ┆ N104MT     ┆ 2026-03-01 ┆ … ┆ null       ┆ null      ┆ null      ┆ null      │
│        ┆          ┆            ┆ 13:03:20   ┆   ┆            ┆           ┆           ┆           │
│ a0180f ┆ null     ┆ N105J      ┆ 2026-03-01 ┆ … ┆ null       ┆ null      ┆ null      ┆ null      │
│        ┆          ┆            ┆ 12:31:49   ┆   ┆            ┆           ┆           ┆           │
│ a01be7 ┆ null     ┆ N106KH     ┆ 2026-03-01 ┆ … ┆ null       ┆ null      ┆ null      ┆ null      │
│        ┆          ┆            ┆ 20:09:38   ┆   ┆            ┆           ┆           ┆           │
│ …      ┆ …        ┆ …          ┆ …          ┆ … ┆ …          ┆ …         ┆ …         ┆ …         │
│ adc204 ┆ null     ┆ N986G      ┆ 2026-03-01 ┆ … ┆ null       ┆ null      ┆ null      ┆ null      │
│        ┆          ┆            ┆ 13:01:50   ┆   ┆            ┆           ┆           ┆           │
│ adcca3 ┆ null     ┆ N989AR     ┆ 2026-03-01 ┆ … ┆ null       ┆ null      ┆ null      ┆ null      │
│        ┆          ┆            ┆ 03:37:25   ┆   ┆            ┆           ┆           ┆           │
│ adcca3 ┆ null     ┆ N989AR     ┆ 2026-03-01 ┆ … ┆ null       ┆ null      ┆ null      ┆ null      │
│        ┆          ┆            ┆ 18:43:12   ┆   ┆            ┆           ┆           ┆           │
│ add15f ┆ null     ┆ N99MB      ┆ 2026-03-01 ┆ … ┆ null       ┆ null      ┆ null      ┆ null      │
│        ┆          ┆            ┆ 18:45:37   ┆   ┆            ┆           ┆           ┆           │
│ add373 ┆ null     ┆ N990JH     ┆ 2026-03-01 ┆ … ┆ null       ┆ null      ┆ null      ┆ null      │
│        ┆          ┆            ┆ 06:04:28   ┆   ┆            ┆           ┆           ┆           │
└────────┴──────────┴────────────┴────────────┴───┴────────────┴───────────┴───────────┴───────────┘

In [9]:
df.filter(pl.col("icao") == "a003a8")

shape: (3, 51)
┌────────┬──────────┬────────────┬────────────┬───┬────────────┬───────────┬───────────┬───────────┐
│ icao   ┆ callsign ┆ registrati ┆ takeoff_ti ┆ … ┆ first_mess ┆ last_mess ┆ first_mes ┆ last_mess │
│ ---    ┆ ---      ┆ on         ┆ me         ┆   ┆ age_time_d ┆ age_time_ ┆ sage_dist ┆ age_dista │
│ str    ┆ str      ┆ ---        ┆ ---        ┆   ┆ iff        ┆ diff      ┆ ance_to_t ┆ nce_to_la │
│        ┆          ┆ str        ┆ datetime[m ┆   ┆ ---        ┆ ---       ┆ ake…      ┆ ndi…      │
│        ┆          ┆            ┆ s]         ┆   ┆ duration[m ┆ duration[ ┆ ---       ┆ ---       │
│        ┆          ┆            ┆            ┆   ┆ s]         ┆ ms]       ┆ f64       ┆ f64       │
╞════════╪══════════╪════════════╪════════════╪═══╪════════════╪═══════════╪═══════════╪═══════════╡
│ a003a8 ┆ null     ┆ null       ┆ null       ┆ … ┆ null       ┆ null      ┆ null      ┆ null      │
│ a003a8 ┆ null     ┆ null       ┆ null       ┆ … ┆ null       ┆ null      ┆ null      ┆ null      │
│ a003a8 ┆ null     ┆ N10PH      ┆ 2026-03-01 ┆ … ┆ null       ┆ null      ┆ null      ┆ null      │
│        ┆          ┆            ┆ 18:08:13   ┆   ┆            ┆           ┆           ┆           │
└────────┴──────────┴────────────┴────────────┴───┴────────────┴───────────┴───────────┴───────────┘

In [ ]:
mismatches = df.filter(pl.col("match_status") != "both")
mismatch_summary = (
    mismatches.group_by("icao")
    .agg(
        (pl.col("match_status") == "df0_only").sum().alias("df0_only"),
        (pl.col("match_status") == "df1_only").sum().alias("df1_only"),
    )
    .sort("icao")
)

confirmed_gold_error_icaos = [
    "a1a4a7", "a1c2e3", "a1d684", "a3a1dc", "a3e348",
    "a63c0b", "a6ea99", "a875ab", "adccd0",
]
confirmed_both_error_icaos = ["a1e6b9"]

mismatch_classification = mismatch_summary.with_columns(
    pl.when(pl.col("icao").is_in(confirmed_both_error_icaos))
    .then(pl.lit("both"))
    .when(pl.col("icao").is_in(confirmed_gold_error_icaos))
    .then(pl.lit("df1_gold_incorrect"))
    .otherwise(pl.lit("adsbx_source_incorrect"))
    .alias("classification")
)
mismatch_classification

## Manual review of direct ADSB-X flight mismatches

This is the direct ADSB-X flight source (`get_flights(..., algorithm="adsbx")`), not the PlaneQuery flight algorithm using ADSB-X messages.

### Summary

- **6,244 true positives, 31 false positives, and 484 false negatives**
- **418 mismatched ICAOs / 515 mismatched rows**
- **Confirmed df1/gold errors:** 9 ICAOs
- **Both sources incorrect:** 1 ICAO
- **Direct ADSB-X source failures:** 408 ICAOs

### Mismatch error percentages

Percentages use the 418 mismatched ICAOs as the denominator.

| Test set Error (%) | Gold-Dataset Error (%) | Error in both (%) |
|---:|---:|---:|
| 97.61% | 2.15% | 0.24% |

The direct ADSB-X failures are overwhelmingly missing flights. A smaller group merges multiple SFDPS legs into a single long flight or truncates an international/low-coverage flight. The `mismatch_classification` dataframe above contains every ICAO and its category.

### Confirmed df1/gold errors

| ICAO | Reason |
|---|---|
| `a1a4a7` | ADSB-X correctly separates KBHM-KNEW-KBHM; df1 combines it. |
| `a1c2e3` | The real KAPF departure is around 20:33, not 18:19. |
| `a1d684` | ADSB-X correctly separates KACT-KTYR-KACT; df1 combines it. |
| `a3a1dc` | KRBD-KMKY departs around 21:10; df1 reuses 18:11. |
| `a3e348` | FA54-KHOU departs around 17:57; df1 reuses 15:07. |
| `a63c0b` | KENW-KBNA departs around 16:25; df1 reuses 12:48. |
| `a6ea99` | The real KGYY departure is around 16:36, not 15:30. |
| `a875ab` | KBKL-KLNS departs around 10:38; df1 reuses 06:12. |
| `adccd0` | KPHL-KHPN departs around 17:43; df1 reuses 14:03. |

### Both sources are incorrect

- `a1e6b9`: df1 gives the wrong KHOU-KDAL departure time, while the direct ADSB-X source also omits the KDAL-KSTL leg.

> **Comparison caveat:** `compare_airports=False` means airport-only disagreements can remain labeled `both`. Use `same_takeoff_airport_ident`, `same_landing_airport_ident`, and `same_airport_ident` when reviewing endpoint accuracy.