In [ ]:
# this may be example of my sfdps algorithm failing.

# Search SFDPS logs for `a003a8` on `2026-03-01`

This notebook searches the local derived SFDPS flights, algorithm output, SFDPS intermediate parquet logs, and raw gzipped SFDPS logs for the target ICAO. It also carries forward related identifiers found in derived data, such as registration and callsign, so later cells can catch raw log rows that do not include the ICAO address directly.

In [1]:
from __future__ import annotations

import gzip
import os
import re
import sys
from datetime import date
from pathlib import Path

import polars as pl

TARGET_DATE = date(2026, 3, 1)
TARGET_ICAO = "a003a8"
INITIAL_RELATED_VALUES = {TARGET_ICAO, "A003A8", "N10PH"}

REPO_ROOT = Path.cwd()
if REPO_ROOT.name == "notebooks":
    REPO_ROOT = REPO_ROOT.parent

sys.path.insert(0, str(REPO_ROOT / "src"))

def day_partition(d: date) -> str:
    return f"year={d.year}/month={d.month:02d}/day={d.day:02d}"

PARTITION = day_partition(TARGET_DATE)
print(REPO_ROOT)
print(PARTITION)

/Users/jonahgoode/Documents/PlaneQuery/Code/planequery-flights-algorithm
year=2026/month=03/day=01

In [2]:
def ordered_unique(paths: list[Path]) -> list[Path]:
    seen = set()
    out = []
    for path in paths:
        resolved = path.expanduser().resolve()
        if resolved not in seen:
            seen.add(resolved)
            out.append(resolved)
    return out

output_dir = Path(os.getenv("OUTPUT_DIR", REPO_ROOT)).expanduser()
candidate_roots = ordered_unique([
    output_dir,
    REPO_ROOT,
    REPO_ROOT.parent / "planequery-data",
])

derived_sfdps_paths = ordered_unique([
    root / "data/flights/sfdps/v1" / PARTITION / "part-0.parquet"
    for root in candidate_roots
])
algorithm_paths = ordered_unique([
    root / "data/flights/algorithm/v1/adsblol" / PARTITION / "flights.parquet"
    for root in candidate_roots
])
intermediate_sfdps_paths = ordered_unique([
    root / "data/intermediate/sfdps-logs" / PARTITION / f"sfdps-logs_{TARGET_DATE:%Y_%m_%d}.parquet"
    for root in candidate_roots
])
raw_sfdps_dirs = ordered_unique([
    root / "data/raw/sfdps-logs" / PARTITION
    for root in candidate_roots
])

for label, paths in {
    "derived SFDPS flights": derived_sfdps_paths,
    "algorithm flights": algorithm_paths,
    "intermediate SFDPS parquet": intermediate_sfdps_paths,
    "raw SFDPS dirs": raw_sfdps_dirs,
}.items():
    print(f"\n{label}")
    for path in paths:
        print("exists" if path.exists() else "missing", path)

derived SFDPS flights
exists /Volumes/T2-SSD/planequery/data/flights/sfdps/v1/year=2026/month=03/day=01/part-0.parquet
exists /Users/jonahgoode/Documents/PlaneQuery/Code/planequery-flights-algorithm/data/flights/sfdps/v1/year=2026/month=03/day=01/part-0.parquet
exists /Users/jonahgoode/Documents/PlaneQuery/Code/planequery-data/data/flights/sfdps/v1/year=2026/month=03/day=01/part-0.parquet

algorithm flights
exists /Volumes/T2-SSD/planequery/data/flights/algorithm/v1/adsblol/year=2026/month=03/day=01/flights.parquet
exists /Users/jonahgoode/Documents/PlaneQuery/Code/planequery-flights-algorithm/data/flights/algorithm/v1/adsblol/year=2026/month=03/day=01/flights.parquet
exists /Users/jonahgoode/Documents/PlaneQuery/Code/planequery-data/data/flights/algorithm/v1/adsblol/year=2026/month=03/day=01/flights.parquet

intermediate SFDPS parquet
exists /Volumes/T2-SSD/planequery/data/intermediate/sfdps-logs/year=2026/month=03/day=01/sfdps-logs_2026_03_01.parquet
missing /Users/jonahgoode/Documents/PlaneQuery/Code/planequery-flights-algorithm/data/intermediate/sfdps-logs/year=2026/month=03/day=01/sfdps-logs_2026_03_01.parquet
missing /Users/jonahgoode/Documents/PlaneQuery/Code/planequery-data/data/intermediate/sfdps-logs/year=2026/month=03/day=01/sfdps-logs_2026_03_01.parquet

raw SFDPS dirs
exists /Volumes/T2-SSD/planequery/data/raw/sfdps-logs/year=2026/month=03/day=01
missing /Users/jonahgoode/Documents/PlaneQuery/Code/planequery-flights-algorithm/data/raw/sfdps-logs/year=2026/month=03/day=01
missing /Users/jonahgoode/Documents/PlaneQuery/Code/planequery-data/data/raw/sfdps-logs/year=2026/month=03/day=01

In [3]:
def contains_any_expr(columns: list[str], values: set[str]) -> pl.Expr:
    escaped = [re.escape(v) for v in values if v]
    if not escaped:
        return pl.lit(False)
    pattern = "(?i)(" + "|".join(sorted(escaped, key=len, reverse=True)) + ")"
    return pl.any_horizontal([
        pl.col(col).cast(pl.String, strict=False).str.contains(pattern).fill_null(False)
        for col in columns
    ])

def read_matches(path: Path, values: set[str], columns: list[str] | None = None) -> pl.DataFrame:
    df = pl.read_parquet(path)
    search_columns = columns or df.columns
    search_columns = [col for col in search_columns if col in df.columns]
    if not search_columns:
        return df.clear()
    return df.filter(contains_any_expr(search_columns, values))

def display_matches(label: str, path: Path, values: set[str], columns: list[str] | None = None) -> pl.DataFrame:
    print(f"\n## {label}")
    print(path)
    if not path.exists():
        print("missing")
        return pl.DataFrame()
    matches = read_matches(path, values, columns=columns)
    print(f"rows: {matches.height}")
    if matches.height:
        display(matches)
    return matches

In [4]:
related_values = set(INITIAL_RELATED_VALUES)

derived_matches = []
for path in derived_sfdps_paths:
    matches = display_matches(
        "derived SFDPS flights",
        path,
        related_values,
        columns=["icao", "registration", "callsign"],
    )
    if matches.height:
        derived_matches.append(matches)
        for col in ["icao", "registration", "callsign"]:
            if col in matches.columns:
                related_values.update(v for v in matches[col].drop_nulls().cast(pl.String).unique().to_list() if v)

print("related values for raw/intermediate searches:", sorted(related_values))

## derived SFDPS flights
/Volumes/T2-SSD/planequery/data/flights/sfdps/v1/year=2026/month=03/day=01/part-0.parquet
rows: 2

shape: (2, 15)
┌────────┬──────────┬────────────┬────────────┬───┬────────────┬────────────┬───────────┬──────────┐
│ icao   ┆ callsign ┆ registrati ┆ takeoff_ti ┆ … ┆ aircraft_t ┆ owner      ┆ aircraft_ ┆ category │
│ ---    ┆ ---      ┆ on         ┆ me         ┆   ┆ ype        ┆ ---        ┆ descripti ┆ ---      │
│ str    ┆ str      ┆ ---        ┆ ---        ┆   ┆ ---        ┆ str        ┆ on        ┆ str      │
│        ┆          ┆ str        ┆ datetime[m ┆   ┆ str        ┆            ┆ ---       ┆          │
│        ┆          ┆            ┆ s]         ┆   ┆            ┆            ┆ str       ┆          │
╞════════╪══════════╪════════════╪════════════╪═══╪════════════╪════════════╪═══════════╪══════════╡
│ a003a8 ┆ TWY116   ┆ N10PH      ┆ 2026-03-01 ┆ … ┆ C56X       ┆ BLUE SKY   ┆ CESSNA    ┆          │
│        ┆          ┆            ┆ 18:08:00   ┆   ┆            ┆ HARBOUR    ┆ 560XL     ┆          │
│        ┆          ┆            ┆            ┆   ┆            ┆ LLC        ┆ Citation  ┆          │
│        ┆          ┆            ┆            ┆   ┆            ┆            ┆ XLS       ┆          │
│ a003a8 ┆ TWY116   ┆ N10PH      ┆ 2026-03-01 ┆ … ┆ C56X       ┆ BLUE SKY   ┆ CESSNA    ┆          │
│        ┆          ┆            ┆ 19:54:00   ┆   ┆            ┆ HARBOUR    ┆ 560XL     ┆          │
│        ┆          ┆            ┆            ┆   ┆            ┆ LLC        ┆ Citation  ┆          │
│        ┆          ┆            ┆            ┆   ┆            ┆            ┆ XLS       ┆          │
└────────┴──────────┴────────────┴────────────┴───┴────────────┴────────────┴───────────┴──────────┘

## derived SFDPS flights
/Users/jonahgoode/Documents/PlaneQuery/Code/planequery-flights-algorithm/data/flights/sfdps/v1/year=2026/month=03/day=01/part-0.parquet
rows: 2

shape: (2, 15)
┌────────┬──────────┬────────────┬────────────┬───┬────────────┬────────────┬───────────┬──────────┐
│ icao   ┆ callsign ┆ registrati ┆ takeoff_ti ┆ … ┆ aircraft_t ┆ owner      ┆ aircraft_ ┆ category │
│ ---    ┆ ---      ┆ on         ┆ me         ┆   ┆ ype        ┆ ---        ┆ descripti ┆ ---      │
│ str    ┆ str      ┆ ---        ┆ ---        ┆   ┆ ---        ┆ str        ┆ on        ┆ str      │
│        ┆          ┆ str        ┆ datetime[m ┆   ┆ str        ┆            ┆ ---       ┆          │
│        ┆          ┆            ┆ s]         ┆   ┆            ┆            ┆ str       ┆          │
╞════════╪══════════╪════════════╪════════════╪═══╪════════════╪════════════╪═══════════╪══════════╡
│ a003a8 ┆ TWY116   ┆ N10PH      ┆ 2026-03-01 ┆ … ┆ C56X       ┆ BLUE SKY   ┆ CESSNA    ┆          │
│        ┆          ┆            ┆ 18:08:00   ┆   ┆            ┆ HARBOUR    ┆ 560XL     ┆          │
│        ┆          ┆            ┆            ┆   ┆            ┆ LLC        ┆ Citation  ┆          │
│        ┆          ┆            ┆            ┆   ┆            ┆            ┆ XLS       ┆          │
│ a003a8 ┆ TWY116   ┆ N10PH      ┆ 2026-03-01 ┆ … ┆ C56X       ┆ BLUE SKY   ┆ CESSNA    ┆          │
│        ┆          ┆            ┆ 19:54:00   ┆   ┆            ┆ HARBOUR    ┆ 560XL     ┆          │
│        ┆          ┆            ┆            ┆   ┆            ┆ LLC        ┆ Citation  ┆          │
│        ┆          ┆            ┆            ┆   ┆            ┆            ┆ XLS       ┆          │
└────────┴──────────┴────────────┴────────────┴───┴────────────┴────────────┴───────────┴──────────┘

## derived SFDPS flights
/Users/jonahgoode/Documents/PlaneQuery/Code/planequery-data/data/flights/sfdps/v1/year=2026/month=03/day=01/part-0.parquet
rows: 2

shape: (2, 15)
┌────────┬──────────┬────────────┬────────────┬───┬────────────┬────────────┬───────────┬──────────┐
│ icao   ┆ callsign ┆ registrati ┆ takeoff_ti ┆ … ┆ aircraft_t ┆ owner      ┆ aircraft_ ┆ category │
│ ---    ┆ ---      ┆ on         ┆ me         ┆   ┆ ype        ┆ ---        ┆ descripti ┆ ---      │
│ str    ┆ str      ┆ ---        ┆ ---        ┆   ┆ ---        ┆ str        ┆ on        ┆ str      │
│        ┆          ┆ str        ┆ datetime[m ┆   ┆ str        ┆            ┆ ---       ┆          │
│        ┆          ┆            ┆ s]         ┆   ┆            ┆            ┆ str       ┆          │
╞════════╪══════════╪════════════╪════════════╪═══╪════════════╪════════════╪═══════════╪══════════╡
│ a003a8 ┆ TWY116   ┆ N10PH      ┆ 2026-03-01 ┆ … ┆ C56X       ┆ BLUE SKY   ┆ CESSNA    ┆          │
│        ┆          ┆            ┆ 18:08:00   ┆   ┆            ┆ HARBOUR    ┆ 560XL     ┆          │
│        ┆          ┆            ┆            ┆   ┆            ┆ LLC        ┆ Citation  ┆          │
│        ┆          ┆            ┆            ┆   ┆            ┆            ┆ XLS       ┆          │
│ a003a8 ┆ TWY116   ┆ N10PH      ┆ 2026-03-01 ┆ … ┆ C56X       ┆ BLUE SKY   ┆ CESSNA    ┆          │
│        ┆          ┆            ┆ 19:54:00   ┆   ┆            ┆ HARBOUR    ┆ 560XL     ┆          │
│        ┆          ┆            ┆            ┆   ┆            ┆ LLC        ┆ Citation  ┆          │
│        ┆          ┆            ┆            ┆   ┆            ┆            ┆ XLS       ┆          │
└────────┴──────────┴────────────┴────────────┴───┴────────────┴────────────┴───────────┴──────────┘

related values for raw/intermediate searches: ['A003A8', 'N10PH', 'TWY116', 'a003a8']

In [5]:
algorithm_matches = []
for path in algorithm_paths:
    matches = display_matches(
        "algorithm flights",
        path,
        related_values,
        columns=["icao", "registration", "callsign", "flight_id"],
    )
    if matches.height:
        algorithm_matches.append(matches)

## algorithm flights
/Volumes/T2-SSD/planequery/data/flights/algorithm/v1/adsblol/year=2026/month=03/day=01/flights.parquet
rows: 1

shape: (1, 28)
┌────────┬──────────┬────────────┬────────────┬───┬──────────┬────────────┬────────────┬───────────┐
│ icao   ┆ callsign ┆ registrati ┆ takeoff_ti ┆ … ┆ category ┆ flight_id  ┆ takeoff_ai ┆ landing_a │
│ ---    ┆ ---      ┆ on         ┆ me         ┆   ┆ ---      ┆ ---        ┆ rport_scor ┆ irport_sc │
│ str    ┆ str      ┆ ---        ┆ ---        ┆   ┆ str      ┆ str        ┆ e          ┆ ore       │
│        ┆          ┆ str        ┆ datetime[m ┆   ┆          ┆            ┆ ---        ┆ ---       │
│        ┆          ┆            ┆ s]         ┆   ┆          ┆            ┆ f64        ┆ f64       │
╞════════╪══════════╪════════════╪════════════╪═══╪══════════╪════════════╪════════════╪═══════════╡
│ a003a8 ┆          ┆            ┆ 2026-03-01 ┆ … ┆ A2       ┆ a003a8_202 ┆ 0.4522     ┆ 0.999969  │
│        ┆          ┆            ┆ 19:44:39.6 ┆   ┆          ┆ 6-03-01_19 ┆            ┆           │
│        ┆          ┆            ┆ 70         ┆   ┆          ┆ -44        ┆            ┆           │
└────────┴──────────┴────────────┴────────────┴───┴──────────┴────────────┴────────────┴───────────┘

## algorithm flights
/Users/jonahgoode/Documents/PlaneQuery/Code/planequery-flights-algorithm/data/flights/algorithm/v1/adsblol/year=2026/month=03/day=01/flights.parquet
rows: 1

shape: (1, 28)
┌────────┬──────────┬────────────┬────────────┬───┬──────────┬────────────┬────────────┬───────────┐
│ icao   ┆ callsign ┆ registrati ┆ takeoff_ti ┆ … ┆ category ┆ flight_id  ┆ takeoff_ai ┆ landing_a │
│ ---    ┆ ---      ┆ on         ┆ me         ┆   ┆ ---      ┆ ---        ┆ rport_scor ┆ irport_sc │
│ str    ┆ str      ┆ ---        ┆ ---        ┆   ┆ str      ┆ str        ┆ e          ┆ ore       │
│        ┆          ┆ str        ┆ datetime[m ┆   ┆          ┆            ┆ ---        ┆ ---       │
│        ┆          ┆            ┆ s]         ┆   ┆          ┆            ┆ f64        ┆ f64       │
╞════════╪══════════╪════════════╪════════════╪═══╪══════════╪════════════╪════════════╪═══════════╡
│ a003a8 ┆          ┆            ┆ 2026-03-01 ┆ … ┆ A2       ┆ a003a8_202 ┆ 0.107034   ┆ 0.999966  │
│        ┆          ┆            ┆ 19:44:39.6 ┆   ┆          ┆ 6-03-01_19 ┆            ┆           │
│        ┆          ┆            ┆ 70         ┆   ┆          ┆ -44        ┆            ┆           │
└────────┴──────────┴────────────┴────────────┴───┴──────────┴────────────┴────────────┴───────────┘

## algorithm flights
/Users/jonahgoode/Documents/PlaneQuery/Code/planequery-data/data/flights/algorithm/v1/adsblol/year=2026/month=03/day=01/flights.parquet
rows: 1

shape: (1, 28)
┌────────┬──────────┬────────────┬────────────┬───┬──────────┬────────────┬────────────┬───────────┐
│ icao   ┆ callsign ┆ registrati ┆ takeoff_ti ┆ … ┆ category ┆ flight_id  ┆ takeoff_ai ┆ landing_a │
│ ---    ┆ ---      ┆ on         ┆ me         ┆   ┆ ---      ┆ ---        ┆ rport_scor ┆ irport_sc │
│ str    ┆ str      ┆ ---        ┆ ---        ┆   ┆ str      ┆ str        ┆ e          ┆ ore       │
│        ┆          ┆ str        ┆ datetime[m ┆   ┆          ┆            ┆ ---        ┆ ---       │
│        ┆          ┆            ┆ s]         ┆   ┆          ┆            ┆ f64        ┆ f64       │
╞════════╪══════════╪════════════╪════════════╪═══╪══════════╪════════════╪════════════╪═══════════╡
│ a003a8 ┆          ┆            ┆ 2026-03-01 ┆ … ┆ A2       ┆ a003a8_202 ┆ 0.107034   ┆ 0.999966  │
│        ┆          ┆            ┆ 19:44:39.6 ┆   ┆          ┆ 6-03-01_19 ┆            ┆           │
│        ┆          ┆            ┆ 70         ┆   ┆          ┆ -44        ┆            ┆           │
└────────┴──────────┴────────────┴────────────┴───┴──────────┴────────────┴────────────┴───────────┘

In [6]:
intermediate_matches = []
for path in intermediate_sfdps_paths:
    if not path.exists():
        print("missing", path)
        continue

    schema = pl.read_parquet_schema(path)
    print(f"\nintermediate columns in {path.name}: {len(schema)}")
    likely_id_cols = [
        col for col in schema
        if any(token in col.lower() for token in ["aircraft", "registration", "ident", "address", "gufi", "callsign"])
    ]
    print("likely id columns:", likely_id_cols)

    matches = display_matches(
        "intermediate SFDPS parquet, likely id columns",
        path,
        related_values,
        columns=likely_id_cols,
    )
    if matches.height:
        intermediate_matches.append(matches)

    # Second pass over all columns, slower but useful when the value is buried in an unexpected field.
    all_col_matches = display_matches("intermediate SFDPS parquet, all columns", path, related_values)
    if all_col_matches.height:
        intermediate_matches.append(all_col_matches)

intermediate columns in sfdps-logs_2026_03_01.parquet: 563
likely id columns: ['aircraft_identification', 'gufi', 'sup_fdps_gufi', 'aircraft_address', 'aircraft_registration', 'aircraft_type', 'aircraftDescription.capabilities.communication.otherDataLinkCapabilities', 'aircraftDescription.capabilities.communication.selectiveCallingCode', 'aircraftDescription.capabilities.communication.communicationCode', 'aircraftDescription.capabilities.communication.dataLinkCode', 'aircraftDescription.capabilities.navigation.otherNavigationCapabilities', 'aircraftDescription.capabilities.navigation.navigationCode', 'aircraftDescription.capabilities.navigation.performanceBasedCode', 'aircraftDescription.capabilities.surveillance.otherSurveillanceCapabilities', 'aircraftDescription.capabilities.surveillance.surveillanceCode', 'aircraftDescription.accuracy.cmsFieldType[0].phase', 'aircraftDescription.accuracy.cmsFieldType[0]', 'aircraftDescription.accuracy.cmsFieldType[1].phase', 'aircraftDescription.accuracy.cmsFieldType[1]', 'aircraftDescription.accuracy.cmsFieldType[2].phase', 'aircraftDescription.accuracy.cmsFieldType[2]', 'agreed.route.adaptedArrivalDepartureRoute.nasRouteIdentifier', 'enRoute.pointout.receivingUnit.unitIdentifier', 'enRoute.pointout.receivingUnit.sectorIdentifier', 'aircraft_performance', 'tfms_special_aircraft_qualifier', 'aircraft_quantity', 'agreed.route.nasadaptedArrivalRoute.nasRouteIdentifier', 'agreed.route.adaptedDepartureRoute.nasRouteIdentifier', 'aircraftDescription.capabilities.communication.otherCommunicationCapabilities', 'enRoute.pointout.receivingUnit[0].unitIdentifier', 'enRoute.pointout.receivingUnit[0].sectorIdentifier', 'enRoute.pointout.receivingUnit[1].unitIdentifier', 'enRoute.pointout.receivingUnit[1].sectorIdentifier', 'aircraftDescription.accuracy.cmsFieldType.phase', 'aircraftDescription.accuracy.cmsFieldType', 'flightIdentificationPrevious.computerId', 'flightIdentificationPrevious.siteSpecificPlanId', 'flightIdentificationPrevious.aircraftIdentification', 'enRoute.pointout.receivingUnit[2].unitIdentifier', 'enRoute.pointout.receivingUnit[2].sectorIdentifier', 'enRoute.pointout.receivingUnit[3].unitIdentifier', 'enRoute.pointout.receivingUnit[3].sectorIdentifier']

## intermediate SFDPS parquet, likely id columns
/Volumes/T2-SSD/planequery/data/intermediate/sfdps-logs/year=2026/month=03/day=01/sfdps-logs_2026_03_01.parquet
rows: 95

shape: (95, 563)
┌────────┬────────┬────────┬─────────────┬───┬─────────────┬─────────────┬────────────┬────────────┐
│ centre ┆ source ┆ system ┆ timestamp   ┆ … ┆ agreed.rout ┆ requestedAl ┆ assignedAl ┆ enRoute.al │
│ ---    ┆ ---    ┆ ---    ┆ ---         ┆   ┆ e.expandedR ┆ titude.vfrO ┆ titude.vfr ┆ ternateAer │
│ str    ┆ str    ┆ str    ┆ str         ┆   ┆ oute.rou…   ┆ nTopPlus    ┆ OnTopPlus  ┆ odrome[3]. │
│        ┆        ┆        ┆             ┆   ┆ ---         ┆ ---         ┆ ---        ┆ …          │
│        ┆        ┆        ┆             ┆   ┆ str         ┆ str         ┆ str        ┆ ---        │
│        ┆        ┆        ┆             ┆   ┆             ┆             ┆            ┆ str        │
╞════════╪════════╪════════╪═════════════╪═══╪═════════════╪═════════════╪════════════╪════════════╡
│ ZMA    ┆ FH     ┆ ATL    ┆ 2026-03-01T ┆ … ┆ null        ┆ null        ┆ null       ┆ null       │
│        ┆        ┆        ┆ 15:10:51.55 ┆   ┆             ┆             ┆            ┆            │
│        ┆        ┆        ┆ 0Z          ┆   ┆             ┆             ┆            ┆            │
│ ZMA    ┆ HX     ┆ ATL    ┆ 2026-03-01T ┆ … ┆ null        ┆ null        ┆ null       ┆ null       │
│        ┆        ┆        ┆ 15:10:51.55 ┆   ┆             ┆             ┆            ┆            │
│        ┆        ┆        ┆ 1Z          ┆   ┆             ┆             ┆            ┆            │
│ ZMA    ┆ AH     ┆ ATL    ┆ 2026-03-01T ┆ … ┆ null        ┆ null        ┆ null       ┆ null       │
│        ┆        ┆        ┆ 16:59:00.10 ┆   ┆             ┆             ┆            ┆            │
│        ┆        ┆        ┆ 7Z          ┆   ┆             ┆             ┆            ┆            │
│ ZMA    ┆ HX     ┆ ATL    ┆ 2026-03-01T ┆ … ┆ null        ┆ null        ┆ null       ┆ null       │
│        ┆        ┆        ┆ 16:59:00.10 ┆   ┆             ┆             ┆            ┆            │
│        ┆        ┆        ┆ 8Z          ┆   ┆             ┆             ┆            ┆            │
│ ZMA    ┆ AH     ┆ ATL    ┆ 2026-03-01T ┆ … ┆ null        ┆ null        ┆ null       ┆ null       │
│        ┆        ┆        ┆ 18:08:23.65 ┆   ┆             ┆             ┆            ┆            │
│        ┆        ┆        ┆ 6Z          ┆   ┆             ┆             ┆            ┆            │
│ …      ┆ …      ┆ …      ┆ …           ┆ … ┆ …           ┆ …           ┆ …          ┆ …          │
│ ZMA    ┆ HZ     ┆ ATL    ┆ 2026-03-01T ┆ … ┆ null        ┆ null        ┆ null       ┆ null       │
│        ┆        ┆        ┆ 20:51:20.71 ┆   ┆             ┆             ┆            ┆            │
│        ┆        ┆        ┆ 2Z          ┆   ┆             ┆             ┆            ┆            │
│ ZMA    ┆ HV     ┆ ATL    ┆ 2026-03-01T ┆ … ┆ null        ┆ null        ┆ null       ┆ null       │
│        ┆        ┆        ┆ 20:52:47.90 ┆   ┆             ┆             ┆            ┆            │
│        ┆        ┆        ┆ 6Z          ┆   ┆             ┆             ┆            ┆            │
│ ZMA    ┆ CL     ┆ ATL    ┆ 2026-03-01T ┆ … ┆ null        ┆ null        ┆ null       ┆ null       │
│        ┆        ┆        ┆ 20:52:47.91 ┆   ┆             ┆             ┆            ┆            │
│        ┆        ┆        ┆ 4Z          ┆   ┆             ┆             ┆            ┆            │
│ ZTL    ┆ FH     ┆ ATL    ┆ 2026-03-01T ┆ … ┆ null        ┆ null        ┆ null       ┆ null       │
│        ┆        ┆        ┆ 22:35:51.64 ┆   ┆             ┆             ┆            ┆            │
│        ┆        ┆        ┆ 9Z          ┆   ┆             ┆             ┆            ┆            │
│ ZTL    ┆ HX     ┆ ATL    ┆ 2026-03-01T ┆ … ┆ null        ┆ null        ┆ null       ┆ null       │
│        ┆        ┆        ┆ 22:35:51.65 ┆   ┆             ┆             ┆            ┆            │
│        ┆        ┆        ┆ 0Z          ┆   ┆             ┆             ┆            ┆            │
└────────┴────────┴────────┴─────────────┴───┴─────────────┴─────────────┴────────────┴────────────┘

## intermediate SFDPS parquet, all columns
/Volumes/T2-SSD/planequery/data/intermediate/sfdps-logs/year=2026/month=03/day=01/sfdps-logs_2026_03_01.parquet
rows: 95

shape: (95, 563)
┌────────┬────────┬────────┬─────────────┬───┬─────────────┬─────────────┬────────────┬────────────┐
│ centre ┆ source ┆ system ┆ timestamp   ┆ … ┆ agreed.rout ┆ requestedAl ┆ assignedAl ┆ enRoute.al │
│ ---    ┆ ---    ┆ ---    ┆ ---         ┆   ┆ e.expandedR ┆ titude.vfrO ┆ titude.vfr ┆ ternateAer │
│ str    ┆ str    ┆ str    ┆ str         ┆   ┆ oute.rou…   ┆ nTopPlus    ┆ OnTopPlus  ┆ odrome[3]. │
│        ┆        ┆        ┆             ┆   ┆ ---         ┆ ---         ┆ ---        ┆ …          │
│        ┆        ┆        ┆             ┆   ┆ str         ┆ str         ┆ str        ┆ ---        │
│        ┆        ┆        ┆             ┆   ┆             ┆             ┆            ┆ str        │
╞════════╪════════╪════════╪═════════════╪═══╪═════════════╪═════════════╪════════════╪════════════╡
│ ZMA    ┆ FH     ┆ ATL    ┆ 2026-03-01T ┆ … ┆ null        ┆ null        ┆ null       ┆ null       │
│        ┆        ┆        ┆ 15:10:51.55 ┆   ┆             ┆             ┆            ┆            │
│        ┆        ┆        ┆ 0Z          ┆   ┆             ┆             ┆            ┆            │
│ ZMA    ┆ HX     ┆ ATL    ┆ 2026-03-01T ┆ … ┆ null        ┆ null        ┆ null       ┆ null       │
│        ┆        ┆        ┆ 15:10:51.55 ┆   ┆             ┆             ┆            ┆            │
│        ┆        ┆        ┆ 1Z          ┆   ┆             ┆             ┆            ┆            │
│ ZMA    ┆ AH     ┆ ATL    ┆ 2026-03-01T ┆ … ┆ null        ┆ null        ┆ null       ┆ null       │
│        ┆        ┆        ┆ 16:59:00.10 ┆   ┆             ┆             ┆            ┆            │
│        ┆        ┆        ┆ 7Z          ┆   ┆             ┆             ┆            ┆            │
│ ZMA    ┆ HX     ┆ ATL    ┆ 2026-03-01T ┆ … ┆ null        ┆ null        ┆ null       ┆ null       │
│        ┆        ┆        ┆ 16:59:00.10 ┆   ┆             ┆             ┆            ┆            │
│        ┆        ┆        ┆ 8Z          ┆   ┆             ┆             ┆            ┆            │
│ ZMA    ┆ AH     ┆ ATL    ┆ 2026-03-01T ┆ … ┆ null        ┆ null        ┆ null       ┆ null       │
│        ┆        ┆        ┆ 18:08:23.65 ┆   ┆             ┆             ┆            ┆            │
│        ┆        ┆        ┆ 6Z          ┆   ┆             ┆             ┆            ┆            │
│ …      ┆ …      ┆ …      ┆ …           ┆ … ┆ …           ┆ …           ┆ …          ┆ …          │
│ ZMA    ┆ HZ     ┆ ATL    ┆ 2026-03-01T ┆ … ┆ null        ┆ null        ┆ null       ┆ null       │
│        ┆        ┆        ┆ 20:51:20.71 ┆   ┆             ┆             ┆            ┆            │
│        ┆        ┆        ┆ 2Z          ┆   ┆             ┆             ┆            ┆            │
│ ZMA    ┆ HV     ┆ ATL    ┆ 2026-03-01T ┆ … ┆ null        ┆ null        ┆ null       ┆ null       │
│        ┆        ┆        ┆ 20:52:47.90 ┆   ┆             ┆             ┆            ┆            │
│        ┆        ┆        ┆ 6Z          ┆   ┆             ┆             ┆            ┆            │
│ ZMA    ┆ CL     ┆ ATL    ┆ 2026-03-01T ┆ … ┆ null        ┆ null        ┆ null       ┆ null       │
│        ┆        ┆        ┆ 20:52:47.91 ┆   ┆             ┆             ┆            ┆            │
│        ┆        ┆        ┆ 4Z          ┆   ┆             ┆             ┆            ┆            │
│ ZTL    ┆ FH     ┆ ATL    ┆ 2026-03-01T ┆ … ┆ null        ┆ null        ┆ null       ┆ null       │
│        ┆        ┆        ┆ 22:35:51.64 ┆   ┆             ┆             ┆            ┆            │
│        ┆        ┆        ┆ 9Z          ┆   ┆             ┆             ┆            ┆            │
│ ZTL    ┆ HX     ┆ ATL    ┆ 2026-03-01T ┆ … ┆ null        ┆ null        ┆ null       ┆ null       │
│        ┆        ┆        ┆ 22:35:51.65 ┆   ┆             ┆             ┆            ┆            │
│        ┆        ┆        ┆ 0Z          ┆   ┆             ┆             ┆            ┆            │
└────────┴────────┴────────┴─────────────┴───┴─────────────┴─────────────┴────────────┴────────────┘

missing /Users/jonahgoode/Documents/PlaneQuery/Code/planequery-flights-algorithm/data/intermediate/sfdps-logs/year=2026/month=03/day=01/sfdps-logs_2026_03_01.parquet
missing /Users/jonahgoode/Documents/PlaneQuery/Code/planequery-data/data/intermediate/sfdps-logs/year=2026/month=03/day=01/sfdps-logs_2026_03_01.parquet

In [7]:
pattern = re.compile("|".join(re.escape(v) for v in sorted(related_values, key=len, reverse=True)), re.IGNORECASE)

raw_hits = []
for raw_dir in raw_sfdps_dirs:
    print("\nraw dir", raw_dir)
    if not raw_dir.exists():
        print("missing")
        continue

    gz_files = sorted(p for p in raw_dir.iterdir() if p.suffix in {".gz", ".gzip"})
    print("gz files", len(gz_files))
    for gz_path in gz_files:
        with gzip.open(gz_path, "rt", encoding="utf-8", errors="replace") as fh:
            for line_number, line in enumerate(fh, start=1):
                if pattern.search(line):
                    raw_hits.append({
                        "path": str(gz_path),
                        "line_number": line_number,
                        "line": line.strip(),
                    })

df_raw_hits = pl.DataFrame(raw_hits) if raw_hits else pl.DataFrame({"path": [], "line_number": [], "line": []})
print("raw line hits", df_raw_hits.height)
display(df_raw_hits)

raw dir /Volumes/T2-SSD/planequery/data/raw/sfdps-logs/year=2026/month=03/day=01
gz files 470

KeyboardInterrupt:

In [ ]:
timeline_frames = []

for df in derived_matches:
    cols = [c for c in ["icao", "callsign", "registration", "takeoff_time", "takeoff_airport_ident", "landing_time", "landing_airport_ident", "aircraft_type", "owner", "aircraft_description"] if c in df.columns]
    timeline_frames.append(df.select(cols).with_columns(pl.lit("derived_sfdps").alias("source")))

for df in algorithm_matches:
    cols = [c for c in ["icao", "callsign", "registration", "takeoff_time", "takeoff_airport_ident", "landing_time", "landing_airport_ident", "first_message_time", "last_message_time", "flight_id"] if c in df.columns]
    timeline_frames.append(df.select(cols).with_columns(pl.lit("algorithm").alias("source")))

if timeline_frames:
    timeline = pl.concat(timeline_frames, how="diagonal_relaxed")
    sort_cols = [c for c in ["takeoff_time", "landing_time", "source"] if c in timeline.columns]
    if sort_cols:
        timeline = timeline.sort(sort_cols)
    display(timeline)
else:
    print("No timeline rows found in derived or algorithm outputs.")